mprove contact form
r
r: failed to push some refs to
'https://github.com/hajzeer/grupacoda-v3-website.git'
hint: Updates were rejected because a pushed branch tip is behind its
remote
hint: counterpart. Check out this branch and integrate the remote
changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for
details.

r: failed to push some refs to
'https://github.com/hajzeer/grupacoda-v3-website.git'
hint: Updates were rejected because a pushed branch tip is behind its
remote
hint: counterpart. Check out this branch and integrate the remote
changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for
details.

error: failed to push some refs to
'https://github.com/hajzeer/grupacoda-v3-website.git'
hint: Updates were rejected because a pushed branch tip is be
remote
hint: counterpart. Check out this branch and integrate the remote
changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for
details.